# SPDX-FileCopyrightText: 2022 Winni Neessen <winni@neessen.dev>
#
# SPDX-License-Identifier: CC0-1.0

blank_issues_enabled: false
contact_links:
  - name: GitHub Community Discussions
    url: https://github.com/gozelle/mail/discussions
    about: If your question is not a feature or a bug, please go to the discussion panel and retrieve if your question already exists before submitting.
